CC=gcc --std=c99 -g

all: median_of_two_sorted_array

median_of_two_sorted_array: median_of_two_sorted_array.c
	$(CC) median_of_two_sorted_array.c -o median_of_two_sorted_array  

clean:
	rm -f *.o median_of_two_sorted_array
